name: Test API
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repo
        # Terminal
        run: git clone https://github.com/KimangKhenng/devops-cadt-2.git
      - name: List folders
        run: ls
