name: LEEMING Deploy to VM
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 167.86.93.59
          username: leeming
          # key: ${{ secrets.SSH_KEY }}
          key: admin
          port: 8899
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd CADT-IDG-DevOps
            git pull
            pm2 restart CADT-DevOps
