name: LEEMING Deploy to VM
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 144.126.138.49
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd lmRepos
            git pull
            pm2 restart lmRepos